import { OpportunityBrief } from '@/shared/types';

/**
 * Generates a Markdown representation of an OpportunityBrief.
 */
export function generateMarkdown(brief: OpportunityBrief): string {
  const sections = [
    `# Opportunity Brief: ${brief.inputIdea}`,
    `Generated on: ${new Date(brief.createdAt).toLocaleDateString()}`,
    `ID: ${brief.id}`,
    '',
    '## 1. Opportunity Scorecard',
    `**Overall Score: ${brief.scoring.overallScore} / 10**`,
    '',
    `> "${brief.scoring.scoreExplanation}"`,
    '',
    '### Scoring Breakdown',
    `| Dimension | Score | Explanation |`,
    '| :--- | :--- | :--- |',
    `| Demand Signal | ${brief.scoring.dimensions.demandSignal.score} | ${brief.scoring.dimensions.demandSignal.explanation} |`,
    `| Buyer Clarity | ${brief.scoring.dimensions.buyerClarity.score} | ${brief.scoring.dimensions.buyerClarity.explanation} |`,
    `| Monetization | ${brief.scoring.dimensions.monetizationPotential.score} | ${brief.scoring.dimensions.monetizationPotential.explanation} |`,
    `| Competition | ${brief.scoring.dimensions.competitionDensity.score} | ${brief.scoring.dimensions.competitionDensity.explanation} |`,
    `| Buildability | ${brief.scoring.dimensions.buildability.score} | ${brief.scoring.dimensions.buildability.explanation} |`,
    '',
    '## 2. Problem Definition',
    `**Core Problem:** ${brief.problemDefinition.coreProblem}`,
    `**Pain Point:** ${brief.problemDefinition.painPoint}`,
    `**Affected Workflows:**`,
    ...brief.problemDefinition.affectedWorkflows.map(w => `- ${w}`),
    `**Urgency:** ${brief.problemDefinition.urgency}`,
    '',
    '## 3. Target Customer',
    `**Segment:** ${brief.targetCustomer.segment}`,
    `**Persona:** ${brief.targetCustomer.persona}`,
    `**Environment:** ${brief.targetCustomer.environment}`,
    `**Buyer vs User:** ${brief.targetCustomer.buyerVsUser}`,
    '',
    '## 4. MVP Scope',
    `**Core Action:** ${brief.mvpScope.coreAction}`,
    `**Features:**`,
    ...brief.mvpScope.features.map(f => `- ${f}`),
    `**Architecture:** ${brief.mvpScope.simplifiedArchitecture}`,
    `**Time-to-Value:** ${brief.mvpScope.timeToValue}`,
    '',
    '## 5. Competitive Landscape',
    `**Market Context:** ${brief.competitiveLandscape.marketContext}`,
    '',
    '**Alternatives:**',
    ...brief.competitiveLandscape.alternatives.map(a => `- **${a.name}** (${a.type}): ${a.description}`),
    '',
    '## 6. Key Risks',
    `### THE KILL SHOT`,
    `> **${brief.keyRisks.killShot}**`,
    '',
    '**Assumptions & Risks:**',
    ...brief.keyRisks.assumptions.map(a => `- ${a.assumption} (**Risk: ${a.riskLevel}**)`),
    '',
    '## 7. Final Verdict',
    `**Bottom Line:** ${brief.finalVerdict.bottomLine}`,
    '',
    '**Success Conditions:**',
    ...brief.finalVerdict.successConditions.map(c => `- ${c}`),
    '',
    '**First Thing to Test:**',
    `> ${brief.finalVerdict.firstTest}`,
  ];

  return sections.join('\n');
}
